/* Autogenerated blob_mailbox_config.h for RP2040 blob mailbox config. */
#pragma once
#define BLOB_MAILBOX_ADDR 0x20040000u
#define BLOB_MAILBOX_MAX 512u
// Region: [BLOB_MAILBOX_ADDR .. BLOB_MAILBOX_ADDR + BLOB_MAILBOX_MAX - 1]
static inline void mailboxSetCancelFlag(uint8_t v);
static inline void mailboxClearCancelFlag();
static inline uint8_t mailboxGetCancelFlag();